name: Python Package CI/CD

on:
  release:
    types: [published]  # Trigger on release published (existing)
  workflow_dispatch:  # Add manual trigger option
    inputs:
      version:
        description: 'Version of the release'
        required: true
        default: 'v1.0.0'  # Default value for the version

permissions:
  contents: read  # Allow the action to read the repository contents
  id-token: write  # Write access for publishing to PyPI

jobs:
  deploy:
    runs-on: ubuntu-latest  # Can be adjusted based on your needs

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine
        pip install -r requirements.txt

    - name: Build the package
      run: |
        python -m build  # Build the package using setuptools

    - name: Publish to PyPI
      run: |
        python -m twine upload dist/*
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}

    - name: Notify success
      run: echo "Package successfully published to PyPI!"
